[2025-04-21T10:19:02.166-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T10:19:02.175-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dw_metastore_pipeline.run_dw_metastore manual__2025-04-21T13:18:57.339615+00:00 [queued]>
[2025-04-21T10:19:02.183-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dw_metastore_pipeline.run_dw_metastore manual__2025-04-21T13:18:57.339615+00:00 [queued]>
[2025-04-21T10:19:02.183-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-21T10:19:02.200-0300] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dw_metastore> on 2025-04-21 13:18:57.339615+00:00
[2025-04-21T10:19:02.203-0300] {standard_task_runner.py:72} INFO - Started process 42267 to run task
[2025-04-21T10:19:02.205-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dw_metastore_pipeline', 'run_dw_metastore', 'manual__2025-04-21T13:18:57.339615+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/q.py', '--cfg-path', '/tmp/tmp9o33hgm4']
[2025-04-21T10:19:02.206-0300] {standard_task_runner.py:105} INFO - Job 76: Subtask run_dw_metastore
[2025-04-21T10:19:02.242-0300] {task_command.py:467} INFO - Running <TaskInstance: dw_metastore_pipeline.run_dw_metastore manual__2025-04-21T13:18:57.339615+00:00 [running]> on host DESKTOP-1GIT60U.
[2025-04-21T10:19:02.300-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dw_metastore_pipeline' AIRFLOW_CTX_TASK_ID='run_dw_metastore' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T13:18:57.339615+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T13:18:57.339615+00:00'
[2025-04-21T10:19:02.300-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-21T10:19:02.310-0300] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-21T10:19:02.311-0300] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "\n#!/bin/bash\nset -x\nexport SPARK_HOME=/opt/spark\nexport SPARK_LOCAL_IP=127.0.0.1\nexport PYTHONPATH=/home/lenovo/airflow/jobs:$PYTHONPATH\n\nmkdir -p /home/lenovo/airflow/spark-warehouse\nmkdir -p /home/lenovo/airflow/metastore_db\nchmod -R 777 /home/lenovo/airflow/spark-warehouse\nchmod -R 777 /home/lenovo/airflow/metastore_db\n\n$SPARK_HOME/bin/spark-submit     --master local[*]     --driver-memory 4g     --conf spark.sql.warehouse.dir=/home/lenovo/airflow/spark-warehouse     --conf spark.sql.catalogImplementation=hive     --conf hive.metastore.uris=''     /home/lenovo/airflow/jobs/jobs_functions/dw_sparkmetastore.py     >> /home/lenovo/airflow/logs/spark_dw.log 2>&1"]
[2025-04-21T10:19:02.318-0300] {subprocess.py:99} INFO - Output:
[2025-04-21T10:19:02.319-0300] {subprocess.py:106} INFO - + export SPARK_HOME=/opt/spark
[2025-04-21T10:19:02.319-0300] {subprocess.py:106} INFO - + SPARK_HOME=/opt/spark
[2025-04-21T10:19:02.319-0300] {subprocess.py:106} INFO - + export SPARK_LOCAL_IP=127.0.0.1
[2025-04-21T10:19:02.320-0300] {subprocess.py:106} INFO - + SPARK_LOCAL_IP=127.0.0.1
[2025-04-21T10:19:02.320-0300] {subprocess.py:106} INFO - + export PYTHONPATH=/home/lenovo/airflow/jobs:/opt/spark/python:/opt/spark/python:
[2025-04-21T10:19:02.320-0300] {subprocess.py:106} INFO - + PYTHONPATH=/home/lenovo/airflow/jobs:/opt/spark/python:/opt/spark/python:
[2025-04-21T10:19:02.320-0300] {subprocess.py:106} INFO - + mkdir -p /home/lenovo/airflow/spark-warehouse
[2025-04-21T10:19:02.320-0300] {subprocess.py:106} INFO - + mkdir -p /home/lenovo/airflow/metastore_db
[2025-04-21T10:19:02.321-0300] {subprocess.py:106} INFO - + chmod -R 777 /home/lenovo/airflow/spark-warehouse
[2025-04-21T10:19:02.323-0300] {subprocess.py:106} INFO - + chmod -R 777 /home/lenovo/airflow/metastore_db
[2025-04-21T10:19:02.325-0300] {subprocess.py:106} INFO - + /opt/spark/bin/spark-submit --master 'local[*]' --driver-memory 4g --conf spark.sql.warehouse.dir=/home/lenovo/airflow/spark-warehouse --conf spark.sql.catalogImplementation=hive --conf hive.metastore.uris= /home/lenovo/airflow/jobs/jobs_functions/dw_sparkmetastore.py
[2025-04-21T10:19:06.528-0300] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-21T10:19:06.533-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-21T10:19:06.537-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dw_metastore_pipeline, task_id=run_dw_metastore, run_id=manual__2025-04-21T13:18:57.339615+00:00, execution_date=20250421T131857, start_date=20250421T131902, end_date=20250421T131906
[2025-04-21T10:19:06.552-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-21T10:19:06.552-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task run_dw_metastore (Bash command failed. The command returned a non-zero exit code 1.; 42267)
Traceback (most recent call last):
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/miniconda3/envs/worker/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-21T10:19:06.569-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-21T10:19:06.579-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T10:19:06.579-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
